
version: "3"

services:
    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress
            dockerfile: dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - wordpress_data:/var/www/wordpress
        networks:
            - network
    
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb
        restart: always
        volumes:
            - mariadb_db:/var/lib/mysql
        networks:
            - network
        env_file:
            - .env
    nginx:
        container_name: nginx
        build: requirements/nginx
        restart: always
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
        networks:
            - network

volumes:
    mariadb_db:
        # driver: local
        # driver_opts:
        #     type: none
        #     device: /goinfre/iouardi/data/mariadb
        #     o: bind
    wordpress_data:
        # driver: local
        # driver_opts:
        #     type: none
        #     device: /goinfre/iouardi/data/wordpress
        #     o: bind

networks:
    network:
     driver: bridge
