
version: "3.9"
services:
    wordpress:
        container_name: wordpress
        depends_on:
            -mariadb
        build:  requirements/wordpress
        restart: always
        env_file:
            - .env
          
        volumes:
            - wordpress_data:/var/www/wordpress
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        restart: always

            
        volumes:
            - mariadb_data:/var/lib/mysql
    nginx:
        container_name: nginx
        build: requirements/nginx
        restart: unless-stopped
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
volumes:
    mariadb_data:
        /var/lib/
    wordpress_data: