
version: "3.9"
services:
    wordpress:
        container_name: wordpress
        build:  requirements/wordpress
        restart: always
        env_file:
            - .env
          
        volumes:
            - wordpress_data:/var/www/html
            - ./wordpress:/var/www/html
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        restart: always

            
        volumes:
            - mariadb_data:/var/lib/mysql
    nginx:
        container_name: nginx
        build: requirements/nginx
        restart: unless-stopped
        ports:
            # - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/html
volumes:
    mariadb_data:
    wordpress_data: