
version: "3"

services:
    wordpress:
        container_name: wordpress
        depends_on:
            -mariadb
        build:
            context: requirements/wordpress
            dockerfile: dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - network
    
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            -network
        env_file:
            - .env
    
    nginx:
        container_name: nginx
        build: requirements/nginx
        restart: always
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - network

volumes:
    driver: local
    driver_opts:
        type: none
        device: /home/vbachele/data/mysql
        o: bind
    wordpress_data:
        driver: local
        driver_opts:
        type: none
        device: /home/vbachele/data/wordpress
        o: bind

networks:
    network:
     driver: bridge